package:
  name: gausspy
  version: 0.1

source:
  git_url: https://github.com/Clyde-fare/gausspy.git
  git_tag: dev
#   path: ../

build:
  number: 0
  
  entry_points:
    - submit_calc = gausspy.g09_pbs:submit_pbs_calc

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
    - ase ==3.8.2.dev
    - ase-extensions ==0.1
    - molmod ==1.01
    - cclib
test:
  commands:
    - submit_calc -h
